### ISSUE TITLE
Support for Gradle

### ISSUE THREAD

**Issue by ernakulgoyal** [ralemy/pf4j-spring-tutorial#3]
Hi @ralemy,

Its a great tutorial, can you please confirm if we can use Gradle as package/build tool.

It would be great if you can you post sample configurations for the same?

Thanks!!!

**Comment by ralemy** [comment]
Hello @ernakulgoyal 
thank you for your feedback.

I would have loved to do so, but unfortunately I don't know much about Gradle. you see, AFAIK, There is nothing that can be done with Maven that can not be done with Gradle, Ant, or any other similar tool. besides, since the tutorial is not about the tools but about plugins for Spring boot applications, I am not sure what value will be added. 

That said, please feel free to put a pull request for a Gradle config and I will happily merge it.
Cheers,
Reza.
